//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5Awesome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCT_TAB_JIRKA
    {
        public string AACCT { get; set; }
        public long ABAL { get; set; }
        public short AREST { get; set; }
        public int AWDL_START { get; set; }
        public short AWDL_LEN { get; set; }
        public long AWDL_LMT { get; set; }
        public long AWDL_TDY { get; set; }
        public Nullable<int> TRN_DT { get; set; }
        public int POS_START { get; set; }
        public short POS_LEN { get; set; }
        public long POS_LMT { get; set; }
        public long POS_TDY { get; set; }
        public short CURRENCY_TYPE { get; set; }
        public Nullable<long> HOLD_AMOUNT { get; set; }
        public Nullable<long> ACTUAL_BAL { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<short> ACCT_SEGMENT { get; set; }
    }
}
